name: Practica final GitHub Actions 
on:
  push:
    branches: [ master ]

jobs:

  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint 
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    needs: [linter_job]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install 
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypress
      - name: Crear result.txt
        run: echo ${{steps.cypress.outcome}} > result.txt
      - name: upload artifac 
        uses: actions/upload-artifact@v3
        with:
          name: update_result
          path: result.txt
  
  add_badge_job:
    runs-on: ubuntu-latest
    needs: [cypress_job]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifac
        uses: actions/download-artifact@v3
        with:
          name: update_result
      - name: Catch result cypress
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: result_cypress
      - name: "Action Readme"
        uses: ./.github/actions/change_readme
        with:
          resultado_cypress: ${{ steps.result_cypress.outputs.cypress_outcome }}
      - name: "Push Readme"
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Vicent Esteve Ferre"
          author_email: "esteve.ferre.vicent@gmail.com"
          message: "Add result Cypress in Readme"
          push: true

  deploy_job:
    runs-on: ubuntu-latest
    needs: [cypress_job]
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Action vercel
          uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-org-id: ${{ secrets.ORG_ID }}
            vercel-project-id: ${{ secrets.PROJECT_ID }}
            working-directory: ./
  
  notification_job:
    runs-on: ubuntu-latest
    needs: [cypress_job]
    steps:
      - name: Action Mailgun
        uses: ./.github/actions/noti_mailgun
        with:
          result_linter_job: ${{needs.linter_job.result}}
          result_cypress_job: ${{needs.cypress_job.result}}
          result_add_badge_job: ${{needs.add_badge_job.result}}
          result_deploy_job: ${{needs.deploy_job.result}}
          API_KEY: ${{secrets.MAILGUN_APIKEY}}
          DOMAIN: ${{secrets.MAILGUN_DOMAIN}}
          destinatario: ${{secrets.destinatario}}
