name: Practica final GitHub Actions 
on:
  push:
    branches: [ master ]

jobs:

  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint 
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    needs: [linter_job]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install 
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypress
      - name: Crear result.txt
        run: echo ${{steps.cypress.outcome}} > result.txt
      - name: upload artifac 
        uses: actions/upload-artifact@v3
        with:
          name: update_result
          path: result.txt
