name: Practica final GitHub Actions 
on:
  push:
    branches: [ master ]

jobs:

  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint 
        uses: actions/checkout@v2
        run: npm install
        run: npm run lint